<?php
$categories = $this->getListingcategories();
$enable_image = $this->getItem()->getCategoryImage();
?>
<div class="row ms-category-level">
    <div class="col-category col-xs-12">
        <div class="row">
            <?php $i=1;foreach($categories as $category): ?>
                <?php $childrens = $this->getProductbycategory($category);
                ?>
                <div class="col-xs-12 col-level <?php if($childrens->getSize()) echo 'parent' ?>">
                    <?php if($childrens->getSize()) :?>
                        <p class="form-group"><a href="<?php echo $category->getUrl() ?>"><?php echo $category->getName() ?></a><small class="mb-level-click glyphicon glyphicon-plus small">&nbsp;</small></p>
                    <?php else:?>
                        <a class="form-group" href="<?php echo $category->getUrl() ?>"><?php echo $category->getName() ?></a>
                    <?php endif;?>
                    <?php if($childrens->getSize()) :?>
                        <div class="col-xs-12 col-sub">
                            <div class="row">
                                <?php foreach($childrens as $children):?>

                                    <div class="col-sm-4 col-xs-6 col-tn-12<?php if($enable_image): ?> text-center<?php else: ?> text-left<?php endif;?> ">
                                        <?php $_imgHtml   = '';
                                        if ($children->getSmallImage()) {
                                            $_imgHtml = '<img src="'.$this->helper("catalog/image")->init($children, "small_image")->resize(135).'" width="135" height="135" alt="'.$this->stripTags($this->getImageLabel($children, "small_image"), null, true) .'" />';
                                        }else{
                                            $_imgHtml = '<img src="'.Mage::getBaseUrl("media").'megamenu/sample_data/small_image.jpg" alt="'.$this->stripTags($children->getName(), null, true).'" title="'.$this->stripTags($children->getName(), null, true).'"/>';
                                        }
                                        ?>
                                        <a class="form-group" href="<?php echo $children->getProductUrl() ?>">
                                            <?php if($enable_image): ?>
                                                <span class="form-group col-category-image"><?php echo $_imgHtml;?></span>
                                            <?php endif;?>
                                            <span><?php echo $children->getName() ?></span>
                                        </a>

                                    </div>
                                <?php endforeach;?>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
                <?php $i++; endforeach;?>
        </div>
    </div>
</div>
