<?php
$categories = $this->getListingcategories();
$columnNumber = $this->getColumnNumber();
$col_index = round(12/$columnNumber,0);
$column = $columnNumber-1;
$enable_image = $this->getItem()->getCategoryImage();
?>
<?php if ($categories->getSize()): ?>
    <div class="row ms-category-dynamic">
        <div class="col-category col-xs-12">
            <div class="row">

                <div class="col-level col-xs-<?php echo $col_index;?>">
                    <?php $i=1;foreach($categories as $category): ?>
                        <?php $childrens = $this->getProductbycategory($category);?>
                        <div class="col-xs-12 form-group<?php if($i==1):?> active<?php endif;?><?php if($childrens->getSize()) :?> parent<?php endif;?><?php if($i == $categories->getSize()):?> last<?php endif;?>">
                            <i class="information" style="display: none" title="dynamic-<?php echo $category->getId();?>" ></i>
                            <a title="<?php echo $category->getName() ?>" href="<?php echo $category->getUrl() ?>"><?php echo $category->getName() ?><?php if($childrens->getSize()) :?><small class="glyphicon glyphicon-chevron-right small">&nbsp;</small><?php endif;?></a>
                        </div>
                        <?php $i++; endforeach;?>
                </div>

                <div class="col-xs-<?php echo 12-$col_index;?> dynamic-content">
                    <?php $i=1;foreach($categories as $category): ?>
                        <?php $childrens = $this->getProductbycategory($category);?>
                        <?php $numbers = count($childrens);
                        $col_index2 = floor(12/$column);
                        switch ($column) {
                            case 5:$col_index2 = 24;
                                break;
                            case 7:$col_index2 = 14;
                                break;
                            case 8:$col_index2 = 125;
                                break;
                            case 9:$col_index2 = 111;
                                break;
                            case 10:$col_index2 = 100;
                                break;
                            case 11:$col_index2 = 909;
                                break;
                            default:
                                break;
                        }
                        $add_cat = 0;

                        if($numbers%$column==0){
                            $num_cat = $numbers/$column;
                        }else{
                            $num_cat = floor($numbers/$column) +1;
                            $add_cat = $numbers%$column;
                        };
                        ?>
                        <?php if($childrens->getSize()) :?>
                            <div class="form-group col-dynamic<?php if($i==1): ?> active<?php endif;?>" id="dynamic-<?php echo $category->getId();?>">
                                <?php $j=1;$k=0; foreach($childrens as $children):?>
                                    <?php if($j==1): ?>
                                        <div class="col-xs-<?php echo $col_index2 ?>">
                                        <?php $k++; endif;?>
                                            <div class="form-group<?php if($enable_image): ?> text-center<?php else: ?> text-left<?php endif;?>">
                                                <?php $_imgHtml   = '';
                                                    if ($children->getSmallImage()) {
                                                        $_imgHtml = '<img src="'.$this->helper("catalog/image")->init($children, "small_image")->resize(135).'" width="135" height="135" alt="'.$this->stripTags($this->getImageLabel($children, "small_image"), null, true) .'" />';
                                                    }else{
                                                        $_imgHtml = '<img src="'.Mage::getBaseUrl("media").'megamenu/sample_data/small_image.jpg" alt="'.$this->stripTags($children->getName(), null, true).'" title="'.$this->stripTags($children->getName(), null, true).'"/>';
                                                    }
                                                ?>
                                                <a href="<?php echo $children->getProductUrl() ?>" title="<?php echo $children->getName();?>">
                                                    <?php if($enable_image): ?>
                                                        <span class="form-group col-category-image"><?php echo $_imgHtml;?></span>
                                                    <?php endif;?>
                                                    <span class="form-group col-category-name"><?php echo $children->getName();?></span>
                                                </a>
                                            </div>
                                    <?php if($j==$num_cat): ?>
                                        </div>
                                        <?php if($add_cat != 0 && $k >= $add_cat) $num_cat= floor($numbers/$column) ; ?>
                                    <?php endif;?>
                                    <?php  if($j<$num_cat) $j++;else $j=1; endforeach;?>

                            </div>
                        <?php endif; ?>
                        <?php $i++; endforeach;?>
                </div>

            </div>
        </div>
    </div>
    <style>
        #submenu-<?php echo $this->getItem()->getId(); ?>{padding-top:0;padding-bottom:0;}
        #submenu-<?php echo $this->getItem()->getId(); ?> .ms-header{margin-bottom:0;}
        #submenu-<?php echo $this->getItem()->getId(); ?> .ms-footer{margin-top:0;}
    </style>
<?php endif; ?>